Feat GitHub actions for Transformer builds
rudderlabs/rudder-transformer pull request #1330
Opened 2022-08-05 06:58 UTC by rahulkumark

## Description of the change
> added GHA workflows for transformer builds and pushing those builds to docker hub

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-08-12 05:57 UTC, rskrishnar requested changes

2022-08-12 05:57 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +          docker run ${{ env.REPO_NAME }}:${{ steps.vars.outputs.version }} npm run testVersionedRouter
if this step is successful, we can push the docker image directly. isn't building the image again in line 57 redundant ?

2022-08-12 05:57 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +        name: Run npm tests - testDestinations on Node.js ${{ matrix.node-version }}
since they are running all the tests inside the docker container, do we need to use `actions/setup-node@v3` for this step ?

2022-08-12 05:57 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +  DOCKER_USER: ${{secrets.DOCKER_USER}}
are we using these environment variables ?

2022-08-12 05:57 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +    strategy:
do we need this step as we are building it only for one version ?

2022-08-12 05:57 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +      - feat-github-actions
can you change branch to `master` to test if the builds are working fine ?

2022-09-01 06:46 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +          docker run ${{ env.REPO_NAME }}:${{ steps.vars.outputs.version }} npm run testVersionedRouter
@saikumarrs any advantages if we combine them ?. we have separated these steps so that we know which command actually failed.

2022-09-01 06:47 UTC, rskrishnar commented on .github/workflows/build-pr.yaml
> +          echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/})"
@saikumarrs we only get the branch. need to check if we can get the commit id.

2022-09-01 06:53 UTC, saikumarrs commented on .github/workflows/build-pr.yaml
> +          echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/})"
The branch name seems fine for now.

2022-10-20 02:33 UTC, closed without merging