feature (new integration): Onboard Monday source
rudderlabs/rudder-transformer pull request #1369
Opened 2022-08-26 04:12 UTC by yashasvibajpai

## Description of the change

>  Onboard Monday source

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-08-31 04:59 UTC, ItsSudip requested changes

2022-08-31 04:59 UTC, ItsSudip commented on v0/sources/monday/transform.js
> +  return false;
```suggestion
  return !!event?.challenge;
```

2022-08-31 04:59 UTC, ItsSudip commented on v0/sources/monday/transform.js
> +    : processEvent(event);
Don't use the ternary operator here.

2022-08-31 05:22 UTC, yashasvibajpai commented on v0/sources/monday/transform.js
> +  return false;
Updated.

2022-08-31 05:24 UTC, yashasvibajpai commented on v0/sources/monday/transform.js
> +    : processEvent(event);
This can be used here.

2022-08-31 09:31 UTC, ItsSudip requested changes

2022-08-31 10:32 UTC, yashasvibajpai commented on v0/sources/monday/transform.js
> +    : processEvent(event);
updated!

2022-08-31 10:42 UTC, ItsSudip submitted a review, later dismissed

2022-09-01 05:07 UTC, utsabc approved these changes

2022-09-01 05:24 UTC, ItsSudip approved these changes

2022-09-01 08:18 UTC, merged