feature: batch user deletion support for appsflyer,mixpanel and clevertap
rudderlabs/rudder-transformer pull request #1537
Opened 2022-11-02 05:57 UTC by mihir-4116

## Description of the change

- as of now for existing destination if we want to delete users then we are doing it one by one. like for every user we are making user deletion request to destination which is impecting the performance of the api
- in this pr for appsflyer,mixpanel and clevertap destination we are making user deletion request in batch since they are supporting batch user deletion
- also, for a perticular user if we don't found required key(ex **userId**) then we will drop that perticular user and proceed for remaining users

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ✅] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ✅] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-11-02 06:25 UTC, utsabc commented on v0/destinations/mp/deleteUsers.js
> +      .build();
We need to handle response properly you
```
const deletionRespones = await httpPOST(endpoint, data, headers);
 const processedDeletionRespones = processAxiosResponse(deletionRespones);
 if ( processedDeletionRespones.status !== 200) {
     throw new ErrorBuilder()
      .setMessage("[Mixpanel]::Deletion Request is not successful")
      .setStatus(processedDeletionRespones.status)
      .build();
 }

2022-11-02 06:25 UTC, utsabc commented on v0/destinations/clevertap/deleteUsers.js
> +      .build();
Need to add correct handling same as below

2022-11-02 06:25 UTC, utsabc commented on v0/destinations/af/deleteUsers.js
> +    if (!response || !response.response) {
We need to update the response handling here as well

2022-11-03 04:45 UTC, ItsSudip requested changes

2022-11-03 04:45 UTC, ItsSudip commented on v0/destinations/clevertap/deleteUsers.js
>      }
Can we verify how many users we can delete in a single batch? I mean is there any limitation in the API in sending userId for deletion?

2022-11-03 04:45 UTC, ItsSudip commented on v0/destinations/mp/deleteUsers.js
> +  const endpoint = "https://api.mixpanel.com/engage#profile-delete";
We need to set the endpoint depending on config.dataResidency.

2022-11-03 04:45 UTC, ItsSudip commented on v0/destinations/mp/deleteUsers.js
> +        $ignore_alias: true
Apart from userId every attribute is the same for all. We can store them in a variable and use, WDYT.

2022-11-03 04:45 UTC, ItsSudip commented on v0/destinations/mp/deleteUsers.js
> +  const deletionRespone = await httpPOST(endpoint, data, headers);
Here also we should verify the limit of API.

2022-11-03 04:52 UTC, utsabc commented on v0/destinations/mp/deleteUsers.js
> +  if (processedDeletionRespone.status !== 200) {
```suggestion
  if (!isHttpStatusSuccess(processedDeletionRespone.status)) {
```
Use this function as success can be in range of 200 to 300

2022-11-03 04:52 UTC, utsabc commented on v0/destinations/clevertap/deleteUsers.js
> +  if (processedDeletionRespone.status !== 200) {
Same here

2022-11-03 06:56 UTC, utsabc submitted a review, later dismissed

2022-11-04 08:53 UTC, ItsSudip approved these changes

2022-11-04 10:04 UTC, anantjain45823 approved these changes

2022-11-04 10:08 UTC, merged

2022-11-06 18:13 UTC, krishna2020 commented on __tests__/data/clevertap_deleteUsers_proxy_input.json
>      }
we need to come up with unit test cases here to validate the batching logic