feat(Clevertap): stringify the Object and Array from payload
rudderlabs/rudder-transformer pull request #1554
Opened 2022-11-07 08:26 UTC by sauravlal15

## Description of the change

> This function stringify the payload attributes if it's an array or objects.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ✅] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-11-07 09:13 UTC, mihir-4116 submitted a review, later dismissed

2022-11-07 15:04 UTC, ItsSudip reviewed
Can we add unit-test cases here?

2022-11-08 10:55 UTC, mihir-4116 approved these changes

2022-11-09 04:46 UTC, ItsSudip submitted a review, later dismissed

2022-11-09 10:20 UTC, ItsSudip requested changes

2022-11-09 10:20 UTC, ItsSudip commented on v0/destinations/clevertap/transform.js
> +    category.forEach(key => {
```suggestion
    Object.keys(payload).forEach(key => {
```

2022-11-09 10:45 UTC, sauravlal15 commented on v0/destinations/clevertap/transform.js
> +    category.forEach(key => {
done

2022-11-09 10:57 UTC, ItsSudip approved these changes

2022-11-09 12:26 UTC, merged