feat(destination): onboard campaign manager
rudderlabs/rudder-transformer pull request #1580
Opened 2022-11-16 05:28 UTC by aashishmalik

## Description of the change

> Onboard Campaign Manager

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-11-16 10:10 UTC, ItsSudip requested changes

2022-11-16 20:54 UTC, aashishmalik commented on v0/destinations/campaign_manager/data/DCMTrackConfig.json
> +  },
I have kept it to be in sync with official documentation.  Are you suggesting pick any one of these 3 . In that case there might be multiple keys and will involve giving preference to 1 property.

2022-11-16 20:55 UTC, aashishmalik commented on v0/destinations/campaign_manager/transform.js
> +      : "dfareporting#conversionsBatchInsertRequest";
properties.requestType will decide between update and requests.

2022-11-17 07:57 UTC, utsabc requested changes

2022-11-17 07:57 UTC, utsabc commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": true
```suggestion
    "required": true,
    "metadata": {   "type": "microSecondTimestamp"  }
     
```

2022-11-17 07:57 UTC, utsabc commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": false
```suggestion
    "destKey": "quantity",
    "sourceKeys": "properties.quantity",
    "metadata": {
        "type": "toNumber"
      },
    "required": false
```

2022-11-17 07:57 UTC, utsabc commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": false
Same here
```suggestion
    "destKey": "value",
   "sourceKeys": [
        "properties.total",
        "properties.value",
        "properties.revenue"
      ],
      "metadata": {
        "type": "toNumber"
      },
    "required": false
```

2022-11-17 07:57 UTC, utsabc commented on v0/destinations/campaign_manager/transform.js
> +  requestJson.timestampMicros = (
This will not be needed

2022-11-17 07:57 UTC, utsabc commented on v0/destinations/campaign_manager/networkHandler.js
> +    return false;
return true

2022-11-17 09:16 UTC, aashishmalik commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": false
done

2022-11-17 09:16 UTC, aashishmalik commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": false
this should be string

2022-11-17 09:16 UTC, aashishmalik commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +    "required": true
done

2022-11-17 09:21 UTC, utsabc submitted a review, later dismissed

2022-11-17 09:57 UTC, ItsSudip requested changes

2022-11-17 09:57 UTC, ItsSudip commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +      "properties.revenue"
```suggestion
      "properties.value",
      "properties.total",
      "properties.revenue"
```

2022-11-17 10:00 UTC, aashishmalik commented on v0/destinations/campaign_manager/data/CampaignManagerTrackConfig.json
> +      "properties.revenue"
done

2022-11-17 10:01 UTC, ItsSudip approved these changes

2022-11-17 10:03 UTC, ItsSudip submitted a review, later dismissed

2022-11-17 10:03 UTC, utsabc submitted a review, later dismissed

2022-11-17 10:13 UTC, ItsSudip approved these changes

2022-11-17 10:14 UTC, utsabc approved these changes

2022-11-17 10:17 UTC, merged