feat: new error types for destinations (webhook, wootric, woopra, yahoo_dsp, zendesk)
rudderlabs/rudder-transformer pull request #1645
Opened 2022-12-08 15:14 UTC by mihir-4116

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-12-13 15:05 UTC, koladilip commented on src/v0/destinations/webhook/transform.js
> +      err.message || "[webhook] Failed to process request"
remove [webhook] prefix

2022-12-13 15:05 UTC, koladilip approved these changes

2022-12-14 10:13 UTC, mihir-4116 commented on src/v0/destinations/webhook/transform.js
> +      err.message || "[webhook] Failed to process request"
updated

2022-12-14 10:15 UTC, saikumarrs requested changes

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/webhook/transform.js
> +      err.message || "[webhook] Failed to process request"
Remove the outer-level try-catch in this method.

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/wootric/util.js
> +      throw new NetworkInstrumentationError(
Is this clearly an instrumentation error?

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/wootric/transform.js
>    }
Based on the `getAccessToken` implementation, this validation may not be required. Double-check that, please.
Also, even if we were to throw any error here, it is definitely not the instrumentation error.

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/wootric/transform.js
> +    throw new NetworkInstrumentationError("Access token is missing");
Same as above.

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/wootric/util.js
> +    throw new NetworkInstrumentationError(
Is this really an instrumentation error? Also, the status is ignored here.

2022-12-14 10:15 UTC, saikumarrs commented on src/v0/destinations/yahoo_dsp/transform.js
> +    throw new NetworkInstrumentationError("Access token is not available");
Same as above.

2022-12-14 13:12 UTC, saikumarrs commented on src/v0/destinations/yahoo_dsp/transform.js
> +    throw new NetworkInstrumentationError("Access token is not available");
Is this addressed?

2022-12-14 13:28 UTC, mihir-4116 commented on src/v0/destinations/yahoo_dsp/transform.js
> +    throw new NetworkInstrumentationError("Access token is not available");
updated

2022-12-14 13:30 UTC, saikumarrs approved these changes

2022-12-14 13:30 UTC, merged