fix: added products array check
rudderlabs/rudder-transformer pull request #1949
Opened 2023-03-15 11:39 UTC by mihir-4116

## Description of the change

- check added for products array
- https://app.bugsnag.com/rudderlabs/rudder-transformer-error-reporter/errors/640f3cce603cda0008147bfc?event_id=640f3cce00b8b00761f70000&i=wh&m=nw&pivot_tab=event

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-03-15 12:01 UTC, saikumarrs requested changes
Let's add some test cases.

2023-03-20 06:48 UTC, shrouti1507 approved these changes

2023-03-20 06:52 UTC, Gauravudia approved these changes

2023-03-21 06:27 UTC, shrouti1507 approved these changes

2023-03-21 06:30 UTC, saikumarrs approved these changes

2023-03-21 06:39 UTC, merged