fix(iterable): added 4 MB payload size check for iterable identify calls batching
rudderlabs/rudder-transformer pull request #2140
Opened 2023-05-08 11:19 UTC by mihir-4116

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-05-15 05:05 UTC, ItsSudip commented on src/v0/destinations/iterable/transform.js
> +    }
This part is repeating can't we move this to a function?

2023-05-16 06:36 UTC, mihir-4116 commented on src/v0/destinations/iterable/transform.js
>  function batchEvents(arrayChunks) {
it was written around an year ago, so i haven't changed anything. probably with the next part of refactoring we can convert it to ES6

2023-05-18 06:08 UTC, ItsSudip reviewed
Can you add some test cases covering the scenario?

2023-05-23 06:01 UTC, anantjain45823 submitted a review, later dismissed

2023-05-31 11:41 UTC, utsabc commented on src/v0/destinations/iterable/config.js
> +const IDENTIFY_MAX_BODY_SIZE = 4000000;
```suggestion
const IDENTIFY_MAX_BODY_SIZE_IN_BYTES = 4000000;
```

2023-06-08 10:56 UTC, mihir-4116 commented on src/v0/destinations/iterable/config.js
> +const IDENTIFY_MAX_BODY_SIZE = 4000000;
updated

2023-06-14 08:30 UTC, utsabc requested changes

2023-06-14 16:19 UTC, mihir-4116 commented on src/v0/destinations/iterable/transform.js
> +            eventResponseList,
Updated

2023-06-15 06:09 UTC, utsabc commented on src/v0/destinations/iterable/transform.js
> +  const messageType = message.type.toLowerCase();
```suggestion
  const messageType = message.type?.toLowerCase();
```

2023-06-15 06:18 UTC, mihir-4116 commented on src/v0/destinations/iterable/transform.js
> +  const messageType = message.type.toLowerCase();
updated

2023-06-15 06:24 UTC, utsabc commented on src/v0/destinations/iterable/util.js
> +  const eventType = message.type.toLowerCase();
I think we should add a common validation for message type in `process` func

2023-06-15 06:55 UTC, utsabc commented on src/v0/destinations/iterable/transform.js
> +        return transformedPayloads;
This logic will add same metadata twice if `responses` is array

2023-06-15 07:04 UTC, utsabc commented on src/v0/destinations/iterable/util.js
> +
Need some clarity here what are we trying to do

2023-07-21 04:57 UTC, mihir-4116 commented
closing this pr as it's showing more changes then expected due to commit mess up
created new pr [here](https://github.com/rudderlabs/rudder-transformer/pull/2390)

2023-07-21 04:57 UTC, closed without merging