fix: shopify metric add
rudderlabs/rudder-transformer pull request #2176
Opened 2023-05-15 18:01 UTC by aashishmalik

## Description of the change

> add shopify shopify_no_cartToken to prometheus

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-05-15 18:02 UTC, aashishmalik commented
https://github.com/rudderlabs/rudder-transformer/blob/a2043e101d349bc79b19795ff06fde473f29a214/src/v0/sources/shopify/util.js

2023-05-15 23:22 UTC, chandumlg commented on src/util/prometheus.js
> +        labelNames: ['sourceType', 'status'],
Please double check the labelset. 

I checked the code and found that timestamp is in the label. Is it required? It will blow up the cardinality.

2023-05-15 23:23 UTC, chandumlg requested changes
Please double check the labelset.

2023-05-16 03:26 UTC, koladilip approved these changes

2023-05-16 04:10 UTC, closed without merging