feat: Shopify SessionId Stitching
rudderlabs/rudder-transformer pull request #2253
Opened 2023-06-09 06:36 UTC by anantjain45823

## Description of the change

> This pull request introduces an enhancement of **sessionId stitching** between Shopify Client-Side and Server-Side events functionality by leveraging the rudderSessionIdentifier event and using of Redis for storing the `cartToken` versus `SessionId` mapping.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-06-11 13:52 UTC, koladilip approved these changes

2023-06-11 13:52 UTC, koladilip commented on src/v0/sources/shopify/transform.js
>        anonymousId = await getAnonymousIdFromDb(message, metricMetadata);
not possible to get both anonid and session id in one call?

2023-06-13 10:24 UTC, mihir-4116 requested changes

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/transform.js
> +      logger.debug(`{{SHOPIFY::}} cartToken maping set call Failed due redis error ${e}`);
`logger.debug(`{{SHOPIFY::}} Failed to set cartToken mapping due to a Redis error: ${e}`);`

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/util.js
> +      logger.debug(`{{SHOPIFY::}} anonymousId get call Failed due redis error ${e}`);
`logger.debug(`{{SHOPIFY::}} Failed to retrieve anonymousId from Redis due to an error: ${e}`);`

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/util.js
> +    logger.debug(`Time: ${new Date()} {{SHOPIFY::}} sessionId get call Failed due redis error ${e}`);
logger.debug(`Time: ${new Date()} {{SHOPIFY::}} Failed to retrieve sessionId from Redis due to an error: ${e}`);

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/util.js
> +    logger.debug(`{{SHOPIFY::}} itemsHash set call Failed due redis error ${e}`);
`logger.debug(`{{SHOPIFY::}} Failed to set itemsHash due to a Redis error: ${e}`);`

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/util.js
> +    logger.debug(`{{SHOPIFY::}} itemsHash get call Failed due redis error ${e}`);
`logger.debug(`{{SHOPIFY::}} Failed to retrieve itemsHash from Redis due to an error: ${e}`);`

2023-06-13 10:24 UTC, mihir-4116 commented on src/v0/sources/shopify/util.js
> +  if (sessionId === null) {
is you create a common isNull function or check if it's available then use it here?

2023-06-19 06:02 UTC, anantjain45823 commented
Moved to #2204

2023-06-19 06:02 UTC, closed without merging