fix: customerIO source bugsnag issue for invalid timestamp
rudderlabs/rudder-transformer pull request #2413
Opened 2023-07-28 10:44 UTC by anantjain45823

## Description of the change

> For customerIo as a source we got a bugsnag alert for[ invalid timestamp](https://rudderlabs.slack.com/archives/C02H8RKK9AA/p1690532249763189) which is getting triggered when `timestamp:"invalid timestamp format"` is passed .
In this PR we have put a check for these **timestamp** using **moment.js library**. So if timestamp is not valid we wont be mapping it respective fields and just overlook it

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-07-31 06:29 UTC, mihir-4116 requested changes

2023-07-31 06:29 UTC, mihir-4116 commented on src/v0/sources/customerio/transform.js
> +    const ts = new Date(timestamp * 1000).toISOString();
keep it `validatedTimeStamp`

2023-07-31 09:55 UTC, anantjain45823 commented on src/v0/sources/customerio/transform.js
> +    const ts = new Date(timestamp * 1000).toISOString();
Done

2023-08-01 05:42 UTC, mihir-4116 approved these changes

2023-08-01 07:15 UTC, sanpj2292 approved these changes

2023-08-01 07:16 UTC, merged