Google pub/sub master
rudderlabs/rudder-transformer pull request #276
Opened 2020-08-27 07:56 UTC by ruchiramoitra

2020-08-31 14:17 UTC, prabrishac requested changes

2020-08-31 14:17 UTC, prabrishac commented on v0/destinations/googlepubsub/transform.js
> +    const topicId = splitPath[3];
check `splitPath` length before accessing 3rd indexed element.

2020-08-31 14:17 UTC, prabrishac commented on v0/destinations/googlepubsub/transform.js
> +    const topicId = splitPath[3];
and handle error.

2020-08-31 14:17 UTC, prabrishac commented on v0/destinations/googlepubsub/transform.js
> +    console.log({
remove console.log

2020-08-31 14:17 UTC, prabrishac commented
minor changes requested.

2020-09-09 11:16 UTC, prabrishac approved these changes

2020-09-09 13:36 UTC, arnab-p approved these changes

2020-09-09 13:36 UTC, merged