chore: add business v1 proxy tests and mocks for Marketo
rudderlabs/rudder-transformer pull request #3116
Opened 2024-02-22 02:05 UTC by yashasvibajpai

## What are the changes introduced in this PR?

Add v1 proxy tests for Marketo

## What is the related Linear task?

Resolves INT-1488

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [ ] My code follows the style guidelines of this project

- [ ] **No breaking changes are being introduced.**

- [ ] All related docs linked with the PR?

- [ ] All changes manually tested?

- [ ] Any documentation changes needed with this change?

- [ ] Is the PR limited to 10 file changes?

- [ ] Is the PR limited to one linear task?

- [ ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

2024-02-22 02:08 UTC, devops-github-rudderstack commented
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3116/test-report.html

2024-02-27 07:16 UTC, utsabc commented on test/integrations/destinations/marketo/dataDelivery/business.ts
> +export const testScenariosForV1API: ProxyV1TestData[] = [
For Marketo there multiple response parsing scenarios where custom status code like 6XX and 7XX are parsed and application level errors are determined that is major use case for business scenarios we should test

2024-03-01 06:41 UTC, utsabc requested changes

2024-03-01 06:41 UTC, utsabc commented on test/integrations/destinations/marketo/dataDelivery/business.ts
> +    successCriteria: 'Should return a 400 status code with empty response',
We already have these tests in `other.ts` if not lets add these there

2024-03-01 06:41 UTC, utsabc commented on test/integrations/destinations/marketo/network.ts
> +      },
This is repeating

2024-03-01 06:41 UTC, utsabc commented on test/integrations/destinations/marketo/network.ts
> +          },
repeating

2024-03-01 21:23 UTC, yashasvibajpai commented on test/integrations/destinations/marketo/network.ts
> +          },
Addressed

2024-03-11 05:29 UTC, utsabc approved these changes

2024-03-12 04:09 UTC, shrouti1507 approved these changes

2024-03-12 04:53 UTC, merged