fix: supporting consent mode for GARL
rudderlabs/rudder-transformer pull request #3120
Opened 2024-02-22 18:16 UTC by shrouti1507

## What are the changes introduced in this PR?

Write a brief explainer on your code changes.

## What is the related Linear task?

Resolves INT-XXX

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [ ] My code follows the style guidelines of this project

- [ ] **No breaking changes are being introduced.**

- [ ] All related docs linked with the PR?

- [ ] All changes manually tested?

- [ ] Any documentation changes needed with this change?

- [ ] Is the PR limited to 10 file changes?

- [ ] Is the PR limited to one linear task?

- [ ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

2024-02-23 09:05 UTC, devops-github-rudderstack commented
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3120/test-report.html

2024-02-27 10:19 UTC, saikumarrs requested changes

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/utils.js
> +          consent: { adUserData: consentParts[0], adPersonalization: consentParts[1] },
Though it's internal, let's use proper naming.

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/transform.js
> +    const sortedPayloadArray = lodash.sortBy(payloadArray, (item) => !item.remove);
Why do we want to sort the array?

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/transform.js
> +      }
Is this scenario feasible?

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/utils.test.js
> +describe('groupUserDataBasedOnConsentLevel', () => {
Also, add a scenario where a consent group contains both add and remove action data.

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/transform.js
> +      createdPayload = { ...createPayload(message, userDataBlock, destination) };
I believe there is no need to use any object spread operator here.

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/transform.js
> +      const finalDataObject = singlePayload.remove || singlePayload.create;
We need to build the response for both operations, right?

2024-02-27 10:19 UTC, saikumarrs commented on src/v0/destinations/google_adwords_remarketing_lists/utils.js
> +function groupUserDataBasedOnConsentLevel(input) {
Can we move this utility outside this destination and make it more generic?

Take the consent field names and supported actions as arguments.

2024-02-27 10:19 UTC, saikumarrs commented on test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts
> +                  params: {
We need to add new test cases for the scenarios where consent data is specified.

2024-02-27 10:19 UTC, saikumarrs commented on test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts
>                params: {
We need to add new test cases for the scenarios where consent data is specified.

2024-02-27 10:19 UTC, saikumarrs commented on test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts
> +                      remove: {
The operation change here. Is this expected?

2024-02-29 13:57 UTC, shrouti1507 commented
raised https://github.com/rudderlabs/rudder-transformer/pull/3143 after discussion. Closing this

2024-02-29 13:57 UTC, closed without merging