chore: add v1 proxy tests for MSL
rudderlabs/rudder-transformer pull request #3130
Opened 2024-02-26 07:07 UTC by yashasvibajpai

## What are the changes introduced in this PR?

>add v1 proxy tests for MSL

## What is the related Linear task?

Resolves INT-XXX

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [ ] My code follows the style guidelines of this project

- [ ] **No breaking changes are being introduced.**

- [ ] All related docs linked with the PR?

- [ ] All changes manually tested?

- [ ] Any documentation changes needed with this change?

- [ ] Is the PR limited to 10 file changes?

- [ ] Is the PR limited to one linear task?

- [ ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

2024-02-26 07:10 UTC, devops-github-rudderstack commented
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3130/test-report.html

2024-03-05 05:23 UTC, utsabc requested changes

2024-03-05 05:23 UTC, utsabc commented on test/integrations/destinations/marketo_static_list/dataDelivery/other.ts
> +              workspaceId: 'default-workspaceId',
Can deduplicate these

2024-03-05 05:23 UTC, utsabc commented on test/integrations/destinations/marketo_static_list/dataDelivery/other.ts
> +                },
Use the generate metadata fxn

2024-03-05 05:23 UTC, utsabc commented on test/integrations/destinations/marketo_static_list/dataDelivery/other.ts
> +                },
Same here

2024-03-05 05:23 UTC, utsabc commented on test/integrations/destinations/marketo_static_list/dataDelivery/other.ts
> +            },
replicated

2024-03-05 05:23 UTC, utsabc commented on test/integrations/destinations/marketo_static_list/dataDelivery/other.ts
> +              errorCategory: 'network',
Lets deduplicate the `statTags` and `metadata`

2024-03-10 15:43 UTC, utsabc approved these changes

2024-03-12 04:08 UTC, shrouti1507 approved these changes

2024-03-12 04:53 UTC, merged