feat: add v3 api support to appsflyer
rudderlabs/rudder-transformer pull request #3412
Opened 2024-05-23 16:22 UTC by shrouti1507

## What are the changes introduced in this PR?

https://dev.appsflyer.com/hc/reference/s2s-events-api3-post

## What is the related Linear task?

Resolves INT-1777

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [ ] My code follows the style guidelines of this project

- [ ] **No breaking changes are being introduced.**

- [ ] All related docs linked with the PR?

- [ ] All changes manually tested?

- [ ] Any documentation changes needed with this change?

- [ ] Is the PR limited to 10 file changes?

- [ ] Is the PR limited to one linear task?

- [ ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

2024-05-23 16:25 UTC, devops-github-rudderstack commented
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3412/test-report.html

2024-05-24 19:17 UTC, yashasvibajpai submitted a review, later dismissed

2024-06-07 06:10 UTC, Gauravudia submitted a review, later dismissed

2024-06-07 06:23 UTC, yashasvibajpai submitted a review, later dismissed

2024-06-07 07:46 UTC, utsabc requested changes

2024-06-07 07:46 UTC, utsabc commented on test/integrations/destinations/af/processor/data.ts
> +          },
Please us the new format of writing test cases its difficult to review such large test files

2024-06-07 07:46 UTC, utsabc commented on test/integrations/destinations/af/processor/data.ts
> +          },
Take klaviyo as reference

2024-06-07 07:56 UTC, utsabc approved these changes

2024-06-07 11:45 UTC, utsabc approved these changes

2024-06-07 13:01 UTC, Gauravudia approved these changes

2024-06-07 13:24 UTC, yashasvibajpai approved these changes

2024-06-07 13:55 UTC, merged