Fix: Mixpanel
rudderlabs/rudder-transformer pull request #348
Opened 2020-10-13 04:30 UTC by prabrishac

2020-10-13 10:43 UTC, prabrishac commented
UTs are yet to be fixed. Once, the review is done, will fix the UTs.

2020-10-16 06:09 UTC, arnab-p requested changes

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/data/MPEventPropertiesConfig.json
> +    "sourceKeys": "request_ip",
Should we give precedence to `context.ip` over `request_ip`?

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/transform.js
> +function getGroupKeys(config) {
Can it be converted to a generic method and move to utils?

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/transform.js
>  function getEventTime(message) {
Move to utils?

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/transform.js
> +function toUnixTimestamp(timestamp) {
Move to utils?

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/transform.js
> +function getTimeDifference(message) {
Move to utils?

2020-10-16 06:09 UTC, arnab-p commented on v0/destinations/mp/transform.js
> +    $ip: message.request_ip,
Precedence to `context.ip`?

2020-10-16 06:10 UTC, arnab-p requested changes
Minor comments

2020-10-19 00:15 UTC, arnab-p approved these changes

2020-10-19 00:15 UTC, merged

2022-02-15 12:36 UTC, mderazon commented
Is there any background for this change ?
Due to this, Rudder is now sending the group id inside an array which appears in Mixpanel like this:
![image](https://user-images.githubusercontent.com/717076/154062726-add68fdb-658d-4078-8586-40965e19434d.png)

I couldn't find any reference in Mixpanel docs that they support this kind of functionality, I saw this question:
https://community.mixpanel.com/sending-data-to-mixpanel-11/single-user-part-of-multiple-groups-5991

But this kind of messes up with Mixpanel's internal group feature that they have which requires each event to have the groupKey sent as an event property as well