multiple products + undefined error
rudderlabs/rudder-transformer pull request #402
Opened 2020-12-03 07:39 UTC by shrouti1507

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2020-12-03 07:43 UTC, ruchiramoitra commented on v0/destinations/am/transform.js
> +    // eslint-disable-next-line no-plusplus
don't disable these.. change i++ to I += 1 . 
for others so check what the es lint is saying search and try to replace.

2020-12-10 11:08 UTC, arnab-p requested changes

2020-12-10 11:08 UTC, arnab-p commented on v0/destinations/am/transform.js
> +/* eslint-disable no-console */
Remove `no-console`

2020-12-10 11:08 UTC, arnab-p commented on v0/destinations/am/transform.js
> +    // eslint-disable-next-line no-undef
Remove line-level `eslint-disable`

2020-12-10 11:08 UTC, arnab-p commented on v0/destinations/am/transform.js
> +  let temp;
Use a meaningful name for variables.

2021-06-10 10:24 UTC, closed without merging