Am cloud revenue
rudderlabs/rudder-transformer pull request #415
Opened 2020-12-15 13:29 UTC by shrouti1507

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2020-12-16 08:42 UTC, prabrishac requested changes

2020-12-16 08:42 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  message.properties.products.forEach(product => {
check whether there is products array in payload

2020-12-16 08:42 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  message.properties.products.forEach(product => {
check if message.properties is there in payload

2020-12-16 08:42 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  if (message.properties.revenue) {
same check for message.properties

2020-12-16 08:42 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  message.properties.products.forEach(product => {
same check for product array

2020-12-16 08:42 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  message.properties.products.forEach(product => {
same check for product array

2020-12-16 08:43 UTC, prabrishac reviewed
We could define less no. of methods and reuse logic.

2020-12-16 10:00 UTC, prabrishac commented on v0/destinations/am/transform.js
> +function bothConditionTrue(message)
Provide meaningful method name.

2020-12-16 10:14 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  RevTrackForOnce.properties.quantity = message.properties.quantity;
Do we need these assignments?

2020-12-22 09:00 UTC, prabrishac requested changes
Some minor review comments to follow code convention.
Please delete file - transform_mine.js
Add method docs (description) for newly introduced methods.

2021-01-04 11:54 UTC, prabrishac requested changes

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +const { compact } = require("lodash");
we should remove it as not used.

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +        if (revenueTypeCalculation > 0) {
can we make it `>=0` ?

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +      if (
The code would be more concise, modular and readable, if we move the below code in some other function.

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +        if (message.properties.revenue > 0) {
same as above

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +        if (message.properties.revenue > 0) {
same as above

2021-01-04 11:54 UTC, prabrishac commented on v0/destinations/am/transform.js
> +    lengthEvent,
better name would be numberOfEvents

2021-01-05 12:31 UTC, prabrishac requested changes

2021-01-05 12:31 UTC, prabrishac commented on v0/destinations/am/transform.js
> +          rawPayload.revenueType = "Purchased";
we should also consider the `message.properties.revenue_type || message.properties.revenueType`

2021-01-05 12:31 UTC, prabrishac commented on v0/destinations/am/transform.js
> +        if (revenueTypeCalculation >= 0) {
we should consider price/revenue of each product to determine revenueType for product purchased event

2021-01-11 06:11 UTC, sayan-mitra approved these changes

2021-01-13 17:26 UTC, prabrishac approved these changes

2021-01-13 17:30 UTC, merged