created this branch from master and added traits
rudderlabs/rudder-transformer pull request #442
Opened 2021-01-15 10:58 UTC by shrouti1507

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-01-20 10:52 UTC, prabrishac requested changes

2021-01-20 10:52 UTC, prabrishac commented on v0/destinations/am/transform.js
> +function passingTraitConfigs(
name - may be `prepareTraitsConfig` ?

2021-01-20 10:52 UTC, prabrishac commented on v0/destinations/am/transform.js
> +function traitsHandler(message, destination) {
name - may be `handleTraits` ?

2021-01-20 10:52 UTC, prabrishac commented on v0/destinations/am/transform.js
> +    sendEvents = getProductPurchasedEvents(message, destination, sendEvents);
remove the revenue related change or rebase it.

2021-01-20 10:52 UTC, prabrishac commented on v0/destinations/am/transform.js
> +      traitObject
can we pass only `traitObject` and the other parameter as string like, `$setOnce` or `$add` and prepare the same in called method?

2021-01-20 16:50 UTC, prabrishac requested changes

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  } else if (messageType === EventType.IDENTIFY) {
we can move this code in `responseBuilderSimple` method.

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +function handlingTraits(message, destination) {
rather, `handleTraits` ?

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  traitsObject[objectToInclude] = new Object();
please remove the lint error

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +  if (traitsObject.hasOwnProperty(property)) {
please remove the lint error.

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +    const objectToInclude = "$setOnce";
`objectToInclude` -> `actionKey`

2021-01-20 16:50 UTC, prabrishac commented on v0/destinations/am/transform.js
> +    const objectToInclude = "$setOnce";
replace the same in other places.

2021-01-27 05:28 UTC, prabrishac approved these changes
Looks good to me 👍

2021-01-27 05:35 UTC, sayan-mitra commented
since the changes are small, let's squash the commits

2021-02-01 07:33 UTC, merged