Gainsight Destination
rudderlabs/rudder-transformer pull request #604
Opened 2021-05-16 15:05 UTC by arajguha

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-05-18 06:33 UTC, ruchiramoitra reviewed
check for nested object/arrays. 
add contract id as discussed.

2021-05-20 10:32 UTC, ruchiramoitra approved these changes
LGTM

2021-05-21 07:06 UTC, arnab-p requested changes
Can we improve the code coverage?

2021-05-21 07:16 UTC, arajguha commented on v0/destinations/gainsight/util.js
> +class CustomError extends Error {
we can move it to util/index.js. wdyt?

2021-05-21 07:17 UTC, arnab-p commented on v0/destinations/gainsight/util.js
> +class CustomError extends Error {
Yeah. or even to a separate file called, util/error.js

2021-05-21 07:17 UTC, arajguha commented on v0/destinations/gainsight/util.js
> +    resp = await axios.post(
the handleResponseRules function has MARKETO hardcoded in the statsd calls. dont we need to change it so it can be usable?

2021-05-21 07:17 UTC, arajguha commented on v0/util/index.js
> +      if (value || value === false || value === 0) {
yes. changing this to if(isDefinedAndNotNull(val))

2021-05-21 07:18 UTC, arnab-p commented on v0/destinations/gainsight/util.js
> +    resp = await axios.post(
Yeah, you can pass the destination information as a parameter and use the same method?

2021-05-21 13:49 UTC, merged