restrict event destructing to 3 levels
rudderlabs/rudder-transformer pull request #666
Opened 2021-06-29 08:46 UTC by Jayachand

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-07-12 06:17 UTC, psrikanth88 requested changes

2021-07-12 06:17 UTC, psrikanth88 commented on warehouse/index.js
> +    if (isObject(input[key]) && (options.sourceCategory == 'cloud' && level < 3)) {
Should it be something like
`isObject(input[key]) && (options.sourceCategory !== 'cloud' || level < 3)`

2021-07-12 06:17 UTC, psrikanth88 commented on warehouse/index.js
> +    if (isObject(input[key]) && (options.sourceCategory == 'cloud' && level < 3)) {
Let us add couple of test cases in `warehouse.test.js`

2021-07-13 08:23 UTC, bipin-rudder approved these changes

2021-07-13 15:25 UTC, psrikanth88 approved these changes

2021-07-13 15:26 UTC, merged