Branch - revamp
rudderlabs/rudder-transformer pull request #667
Opened 2021-07-01 07:43 UTC by akashrpo

add IDFA, IDFV, and ATT parameters

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-07-05 04:05 UTC, arnab-p requested changes

2021-07-05 04:05 UTC, arnab-p commented on v0/destinations/branch/transform.js
> +  if (os.toLowerCase() === "ios") {
Take care null-safety

2021-07-06 08:48 UTC, akashrpo commented on v0/destinations/branch/transform.js
> +  if (os.toLowerCase() === "ios") {
added the null-safety check

2021-07-14 04:27 UTC, ruchiramoitra approved these changes
lgtm

2021-08-03 16:12 UTC, arnab-p approved these changes

2021-08-03 16:12 UTC, merged