feat: add all apple family support
rudderlabs/rudder-transformer pull request #925
Opened 2021-12-29 12:09 UTC by akashrpo

## Description of the change

> add support for all apple family devices

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-12-29 12:20 UTC, saikumarrs commented on v0/util/index.js
> +  );
Helps to easily extend in the future.
```suggestion
  const appleOSNames = ["ios", "watchos", "ipados", "tvos"];
  return appleOSNames.includes(platform.toLowerCase());
```

2021-12-29 12:23 UTC, saikumarrs commented on v0/destinations/clevertap/transform.js
> +        ["ios", "watchos", "ipados", "tvos", "android"].includes(deviceOS)
```suggestion
        (deviceOS === "android" || isAppleFamily(deviceOS))
```

2021-12-29 12:25 UTC, saikumarrs requested changes
Add test cases for all the destinations and souces

2021-12-29 19:05 UTC, akashrpo commented on v0/util/index.js
> +  );
Resolved

2021-12-29 19:05 UTC, akashrpo commented on v0/destinations/clevertap/transform.js
> +        ["ios", "watchos", "ipados", "tvos", "android"].includes(deviceOS)
Resolved

2021-12-29 19:06 UTC, akashrpo commented on v0/util/index.js
> +  );
Refactored

2021-12-29 19:06 UTC, akashrpo commented on v0/destinations/clevertap/transform.js
> +        ["ios", "watchos", "ipados", "tvos", "android"].includes(deviceOS)
Refactored

2021-12-30 04:23 UTC, saikumarrs approved these changes

2021-12-30 05:20 UTC, desusai7 approved these changes

2021-12-30 08:27 UTC, merged