Fix/customer io
rudderlabs/rudder-transformer pull request #938
Opened 2022-01-07 14:23 UTC by desusai7

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-08 03:02 UTC, sanpj2292 commented on v0/destinations/customerio/transform.js
>    "Application Uninstalled"
No new event added for `device registration` ?

2022-01-08 03:08 UTC, sanpj2292 commented on v0/destinations/customerio/transform.js
> +      destination.Config.deviceTokenEventName === eventName)
I think this is different from what was decided.
Basically my perspective of the decision made doesn't involve the destination's configuration(I mean UI), I was thinking more from a perspective that an event(Device Registration) is triggered from the user's side after we get the device token.

Let me know if there is some mis-understanding here

2022-01-10 11:17 UTC, sanpj2292 submitted a review, later dismissed
LGTM

2022-01-10 13:41 UTC, saikumarrs requested changes
Add new unit test cases for the changes introduced

2022-01-11 07:16 UTC, saikumarrs approved these changes

2022-01-11 07:29 UTC, sanpj2292 approved these changes

2022-01-11 07:30 UTC, saikumarrs approved these changes

2022-01-11 07:32 UTC, merged