MP - Update to use the get methods
rudderlabs/rudder-transformer pull request #985
Opened 2022-02-04 18:03 UTC by akashrpo

## Description of the change

> Update to use the `get` methods for accessing the children.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-06 09:14 UTC, utsabc commented
@akashrpo lets add test cases aswell

2022-02-06 11:02 UTC, akashrpo commented
@utsabc There are no additional implementation changes for any new test cases to get added. Just the way we get values has been modified i.e by using `get` field.

2022-02-06 13:45 UTC, utsabc approved these changes

2022-02-06 15:22 UTC, saikumarrs requested changes
The `event.message` object is never undefined.
Given the above fact, using the `get` method to access the first-level children is a bit overkill for most of the changes here.

2022-02-07 13:36 UTC, utsabc approved these changes

2022-02-08 06:15 UTC, saikumarrs approved these changes

2022-02-08 06:18 UTC, merged